"""Add birth_date and make emp_id nullable

Revision ID: 06444f048d15
Revises: cc7fa5f9f609
Create Date: 2026-02-19 16:39:03.654574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06444f048d15'
down_revision = 'cc7fa5f9f609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.String(length=8), nullable=True))
        batch_op.alter_column('emp_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('clock_in',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('clock_out',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('work_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_attendance_emp_date'))
        batch_op.create_index('ix_attendance_emp_date', ['emp_name', 'work_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_emp_date')
        batch_op.create_index(batch_op.f('ix_attendance_emp_date'), ['emp_id', 'work_date'], unique=False)
        batch_op.alter_column('work_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('clock_out',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('clock_in',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('emp_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
