"""initial_schema

Revision ID: 2d328d13a043
Revises: 
Create Date: 2026-02-23 13:56:05.119803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d328d13a043'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_login_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_admin_login_attempt_ip_created', ['ip', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_login_attempts_ip'), ['ip'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('vision', sa.String(length=30), nullable=True),
    sa.Column('shoes', sa.Integer(), nullable=True),
    sa.Column('tshirt', sa.String(length=10), nullable=True),
    sa.Column('shift', sa.String(length=10), nullable=True),
    sa.Column('posture', sa.String(length=10), nullable=True),
    sa.Column('overtime', sa.String(length=10), nullable=True),
    sa.Column('holiday', sa.String(length=10), nullable=True),
    sa.Column('interview_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('agree', sa.Boolean(), nullable=True),
    sa.Column('advance_pay', sa.String(length=10), nullable=True),
    sa.Column('insurance_type', sa.String(length=20), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_advance_pay'), ['advance_pay'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_holiday'), ['holiday'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_insurance_type'), ['insurance_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_overtime'), ['overtime'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_posture'), ['posture'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_shift'), ['shift'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_updated_at'), ['updated_at'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.String(length=6), nullable=False),
    sa.Column('work_type', sa.String(length=10), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('resign_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'birth_date', name='uq_employee_name_birth')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_name'), ['name'], unique=False)

    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assignee', sa.String(length=50), nullable=True),
    sa.Column('admin_memo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inquiries_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_updated_at'), ['updated_at'], unique=False)

    op.create_table('operation_calendar_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('day_type', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_date', name='uq_operation_calendar_work_date')
    )
    with op.batch_alter_table('operation_calendar_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_calendar_days_work_date'), ['work_date'], unique=False)
        batch_op.create_index('ix_operation_calendar_work_date', ['work_date'], unique=False)

    op.create_table('advance_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.String(length=6), nullable=False),
    sa.Column('emp_name', sa.String(length=50), nullable=False),
    sa.Column('dept', sa.String(length=50), nullable=True),
    sa.Column('request_month', sa.String(length=7), nullable=False),
    sa.Column('work_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advance_requests', schema=None) as batch_op:
        batch_op.create_index('ix_advance_employee_month', ['employee_id', 'request_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_advance_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advance_requests_request_month'), ['request_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_advance_requests_status'), ['status'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.String(length=6), nullable=False),
    sa.Column('emp_name', sa.String(length=50), nullable=False),
    sa.Column('dept', sa.String(length=50), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.String(length=5), nullable=True),
    sa.Column('clock_out', sa.String(length=5), nullable=True),
    sa.Column('work_type', sa.String(length=20), nullable=False),
    sa.Column('total_work_hours', sa.Float(), nullable=False),
    sa.Column('overtime_hours', sa.Float(), nullable=False),
    sa.Column('night_hours', sa.Float(), nullable=False),
    sa.Column('holiday_work_hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_attendance_employee_date')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_employee_date', ['employee_id', 'work_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_work_date'), ['work_date'], unique=False)

    op.create_table('careers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('careers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_careers_application_id'), ['application_id'], unique=False)

    op.create_table('payslips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('emp_name', sa.String(length=50), nullable=False),
    sa.Column('dept', sa.String(length=50), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('salary_mode', sa.String(length=10), nullable=True),
    sa.Column('total_work_hours', sa.Float(), nullable=False),
    sa.Column('ot_hours', sa.Float(), nullable=False),
    sa.Column('night_hours', sa.Float(), nullable=False),
    sa.Column('holiday_hours', sa.Float(), nullable=False),
    sa.Column('base_salary', sa.Integer(), nullable=False),
    sa.Column('ot_pay', sa.Integer(), nullable=False),
    sa.Column('night_pay', sa.Integer(), nullable=False),
    sa.Column('holiday_pay', sa.Integer(), nullable=False),
    sa.Column('gross', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('insurance', sa.Integer(), nullable=False),
    sa.Column('advance_deduction', sa.Integer(), nullable=False),
    sa.Column('net', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'month', name='uq_payslip_employee_month')
    )
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.create_index('ix_payslip_employee_month', ['employee_id', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_payslips_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payslips_month'), ['month'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payslips_month'))
        batch_op.drop_index(batch_op.f('ix_payslips_employee_id'))
        batch_op.drop_index('ix_payslip_employee_month')

    op.drop_table('payslips')
    with op.batch_alter_table('careers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_careers_application_id'))

    op.drop_table('careers')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_work_date'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_employee_id'))
        batch_op.drop_index('ix_attendance_employee_date')

    op.drop_table('attendance_records')
    with op.batch_alter_table('advance_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advance_requests_status'))
        batch_op.drop_index(batch_op.f('ix_advance_requests_request_month'))
        batch_op.drop_index(batch_op.f('ix_advance_requests_employee_id'))
        batch_op.drop_index('ix_advance_employee_month')

    op.drop_table('advance_requests')
    with op.batch_alter_table('operation_calendar_days', schema=None) as batch_op:
        batch_op.drop_index('ix_operation_calendar_work_date')
        batch_op.drop_index(batch_op.f('ix_operation_calendar_days_work_date'))

    op.drop_table('operation_calendar_days')
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inquiries_updated_at'))
        batch_op.drop_index(batch_op.f('ix_inquiries_status'))
        batch_op.drop_index(batch_op.f('ix_inquiries_phone'))
        batch_op.drop_index(batch_op.f('ix_inquiries_name'))
        batch_op.drop_index(batch_op.f('ix_inquiries_email'))
        batch_op.drop_index(batch_op.f('ix_inquiries_created_at'))
        batch_op.drop_index(batch_op.f('ix_inquiries_company'))

    op.drop_table('inquiries')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_name'))

    op.drop_table('employees')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_updated_at'))
        batch_op.drop_index(batch_op.f('ix_applications_timestamp'))
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_shift'))
        batch_op.drop_index(batch_op.f('ix_applications_posture'))
        batch_op.drop_index(batch_op.f('ix_applications_phone'))
        batch_op.drop_index(batch_op.f('ix_applications_overtime'))
        batch_op.drop_index(batch_op.f('ix_applications_name'))
        batch_op.drop_index(batch_op.f('ix_applications_insurance_type'))
        batch_op.drop_index(batch_op.f('ix_applications_holiday'))
        batch_op.drop_index(batch_op.f('ix_applications_gender'))
        batch_op.drop_index(batch_op.f('ix_applications_email'))
        batch_op.drop_index(batch_op.f('ix_applications_advance_pay'))

    op.drop_table('applications')
    with op.batch_alter_table('admin_login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_login_attempts_ip'))
        batch_op.drop_index('ix_admin_login_attempt_ip_created')

    op.drop_table('admin_login_attempts')
    # ### end Alembic commands ###
