"""Add holiday_work_hours

Revision ID: 5b29f1bd1c5e
Revises: e597ca6e2f48
Create Date: 2026-02-19 18:36:41.478479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b29f1bd1c5e'
down_revision = 'e597ca6e2f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('holiday_work_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_column('holiday_work_hours')

    # ### end Alembic commands ###
