"""replace employment_contracts with glosign tables

Revision ID: 64427fd5d4cc
Revises: 71a1ef1ea5e6
Create Date: 2026-02-24 01:45:13.918933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64427fd5d4cc'
down_revision = '71a1ef1ea5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=300), nullable=False),
    sa.Column('file_original_name', sa.String(length=200), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('fields_json', sa.Text(), nullable=True),
    sa.Column('roles_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('final_pdf_path', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['contract_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_template_id'), ['template_id'], unique=False)

    op.create_table('contract_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('role_key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('sign_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('field_values_json', sa.Text(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('sign_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_participants_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_participants_sign_token'), ['sign_token'], unique=True)

    with op.batch_alter_table('employment_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employment_contracts_employee_id'))

    op.drop_table('employment_contracts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'sites', ['site_id'], ['id'])

    op.create_table('employment_contracts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('site_id', sa.INTEGER(), nullable=True),
    sa.Column('contract_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('work_location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('job_description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('hourly_wage', sa.INTEGER(), nullable=False),
    sa.Column('work_hours_per_week', sa.FLOAT(), nullable=False),
    sa.Column('work_days', sa.VARCHAR(length=50), nullable=False),
    sa.Column('work_time_start', sa.VARCHAR(length=5), nullable=False),
    sa.Column('work_time_end', sa.VARCHAR(length=5), nullable=False),
    sa.Column('break_hours', sa.FLOAT(), nullable=False),
    sa.Column('pay_day', sa.INTEGER(), nullable=False),
    sa.Column('holiday_info', sa.TEXT(), nullable=True),
    sa.Column('annual_leave_info', sa.TEXT(), nullable=True),
    sa.Column('special_terms', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('pdf_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employment_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employment_contracts_employee_id'), ['employee_id'], unique=False)

    with op.batch_alter_table('contract_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_participants_sign_token'))
        batch_op.drop_index(batch_op.f('ix_contract_participants_contract_id'))

    op.drop_table('contract_participants')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_template_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_employee_id'))

    op.drop_table('contracts')
    op.drop_table('contract_templates')
    # ### end Alembic commands ###
