"""add employment_contracts and leave_balances tables

Revision ID: 71a1ef1ea5e6
Revises: b2c3d4e5f6g7
Create Date: 2026-02-24 01:14:31.830840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a1ef1ea5e6'
down_revision = 'b2c3d4e5f6g7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employment_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('work_location', sa.String(length=200), nullable=True),
    sa.Column('job_description', sa.String(length=500), nullable=True),
    sa.Column('hourly_wage', sa.Integer(), nullable=False),
    sa.Column('work_hours_per_week', sa.Float(), nullable=False),
    sa.Column('work_days', sa.String(length=50), nullable=False),
    sa.Column('work_time_start', sa.String(length=5), nullable=False),
    sa.Column('work_time_end', sa.String(length=5), nullable=False),
    sa.Column('break_hours', sa.Float(), nullable=False),
    sa.Column('pay_day', sa.Integer(), nullable=False),
    sa.Column('holiday_info', sa.Text(), nullable=True),
    sa.Column('annual_leave_info', sa.Text(), nullable=True),
    sa.Column('special_terms', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('pdf_path', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employment_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employment_contracts_employee_id'), ['employee_id'], unique=False)

    op.create_table('leave_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('entitled', sa.Float(), nullable=False),
    sa.Column('used', sa.Float(), nullable=False),
    sa.Column('remaining', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year', name='uq_leave_employee_year')
    )
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_balances_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_balances_employee_id'))

    op.drop_table('leave_balances')
    with op.batch_alter_table('employment_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employment_contracts_employee_id'))

    op.drop_table('employment_contracts')
    # ### end Alembic commands ###
