"""Initial_migration_after_type_refactor

Revision ID: 809e7556244f
Revises: 
Create Date: 2026-02-15 09:24:22.570626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809e7556244f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('vision', sa.String(length=30), nullable=True),
    sa.Column('shoes', sa.Integer(), nullable=True),
    sa.Column('tshirt', sa.String(length=10), nullable=True),
    sa.Column('shift', sa.String(length=10), nullable=True),
    sa.Column('posture', sa.String(length=10), nullable=True),
    sa.Column('overtime', sa.String(length=10), nullable=True),
    sa.Column('holiday', sa.String(length=10), nullable=True),
    sa.Column('interview_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('agree', sa.Boolean(), nullable=True),
    sa.Column('advance_pay', sa.String(length=10), nullable=True),
    sa.Column('insurance_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('careers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('careers')
    op.drop_table('applications')
    # ### end Alembic commands ###
