"""add birth_date and work_type to advance_requests

Revision ID: 965984a9658c
Revises: 06444f048d15
Create Date: 2026-02-19 16:57:16.864679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965984a9658c'
down_revision = '06444f048d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('work_type', sa.String(length=10), nullable=True))
        batch_op.alter_column('emp_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advance_requests', schema=None) as batch_op:
        batch_op.alter_column('emp_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('work_type')
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
