"""add attendance payslip advance models

Revision ID: cc7fa5f9f609
Revises: d2a7f1c3b9a1
Create Date: 2026-02-19 15:46:57.996444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7fa5f9f609'
down_revision = 'd2a7f1c3b9a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advance_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('emp_name', sa.String(length=50), nullable=False),
    sa.Column('dept', sa.String(length=50), nullable=True),
    sa.Column('request_month', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advance_requests', schema=None) as batch_op:
        batch_op.create_index('ix_advance_emp_month', ['emp_id', 'request_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_advance_requests_emp_id'), ['emp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advance_requests_request_month'), ['request_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_advance_requests_status'), ['status'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('emp_name', sa.String(length=50), nullable=False),
    sa.Column('dept', sa.String(length=50), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.String(length=5), nullable=False),
    sa.Column('clock_out', sa.String(length=5), nullable=False),
    sa.Column('work_type', sa.String(length=10), nullable=False),
    sa.Column('total_work_hours', sa.Float(), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=True),
    sa.Column('night_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_emp_date', ['emp_id', 'work_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_emp_id'), ['emp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_work_date'), ['work_date'], unique=False)

    op.create_table('payslips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('emp_name', sa.String(length=50), nullable=False),
    sa.Column('dept', sa.String(length=50), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('salary_mode', sa.String(length=10), nullable=True),
    sa.Column('total_work_hours', sa.Float(), nullable=True),
    sa.Column('ot_hours', sa.Float(), nullable=True),
    sa.Column('night_hours', sa.Float(), nullable=True),
    sa.Column('base_salary', sa.Integer(), nullable=True),
    sa.Column('ot_pay', sa.Integer(), nullable=True),
    sa.Column('night_pay', sa.Integer(), nullable=True),
    sa.Column('gross', sa.Integer(), nullable=True),
    sa.Column('tax', sa.Integer(), nullable=True),
    sa.Column('insurance', sa.Integer(), nullable=True),
    sa.Column('advance_deduction', sa.Integer(), nullable=True),
    sa.Column('net', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emp_id', 'month', name='uq_payslip_emp_month')
    )
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payslips_emp_id'), ['emp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payslips_month'), ['month'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payslips_month'))
        batch_op.drop_index(batch_op.f('ix_payslips_emp_id'))

    op.drop_table('payslips')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_work_date'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_emp_id'))
        batch_op.drop_index('ix_attendance_emp_date')

    op.drop_table('attendance_records')
    with op.batch_alter_table('advance_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advance_requests_status'))
        batch_op.drop_index(batch_op.f('ix_advance_requests_request_month'))
        batch_op.drop_index(batch_op.f('ix_advance_requests_emp_id'))
        batch_op.drop_index('ix_advance_emp_month')

    op.drop_table('advance_requests')
    # ### end Alembic commands ###
