"""add hire_date resign_date to employees

Revision ID: e597ca6e2f48
Revises: b7b3aa1d5cc1
Create Date: 2026-02-19 17:19:07.106029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e597ca6e2f48'
down_revision = 'b7b3aa1d5cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hire_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('resign_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('resign_date')
        batch_op.drop_column('hire_date')

    # ### end Alembic commands ###
